### ISSUE TITLE
DORA metrics and Deployment Frequency calculation

### ISSUE THREAD

**Issue by basiliskus** [flexion/devops-deployment-metrics#51]
Are the deployment metrics in this repo supposed to follow the [DORA metrics standard](https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance)? 

In case it is, the Deployment Frequency is defined as:

> How often an organization _**successfully**_ releases to production

The current implementation uses _all_ deployments for the calculation, not just the successful ones. Is this intentional?

**Comment by tomwillis608** [comment]
It was deliberate. The metric is based on page 16 of _Accelerate_, which doesn't really specify.  
I have no problem calculated both versions, for example.
