### ISSUE TITLE
Refactoring tasks to improve codebase and help add features needed by Trusted Intermediary 

### ISSUE THREAD

**Issue by basiliskus** [flexion/devops-deployment-metrics#69]
- [x] Refactor code towards following OeSA and clean code guidelines
- [x] Change authentication with github access token so it doesn’t require username
- [x] Add handling of multiple workflows with separate outputs. It currently handles multiple workflows but aggregates into one single output file per metric

**Comment by tomwillis608** [comment]
I like these goals

**Comment by basiliskus** [comment]
Implemented and merged in [PR 72](https://github.com/flexion/devops-deployment-metrics/pull/72)
